<?php

/**
 * @file
 * Contains bedo_platform_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bedo_platform_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bedo_platform_api module.
    case 'help.page.bedo_platform_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('BedoyaTech Platform API') . '</p>';
      return $output;

    default:
  }
}
